export const MOVETYPES = {
  DRAW_FROM_DISCARD: "DrawFromDiscard",
  DRAW_FROM_DECK: "DrawFromShoe",
  DISCARD: "Discard",
  GO_OUT: "GoOut",
  READY_FOR_NEXT_ROUND: "ReadyForNextRound",
};

export const GAMESTATUS = {
  PENDING_TURN: "PENDING_TURN",
  PENDING_DRAW: "PENDING_DRAW",
  PENDING_DISCARD: "PENDING_DISCARD",
  PENDING_OPPONENT_OUT: "PENDING_OPPONENT_OUT",
  PENDING_NEXT_ROUND: "PENDING_NEXT_ROUND",
};

export const GOINGOUTSTATUS = {
  NONE: "NONE",
  GOING: "GOING",
  GONE: "GONE",
};
